version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - cd cicd # change directory to the terraform where the terraform config files are
      - chmod +x install-terraform.sh configure-profile-name.sh terraform-backend.sh apply-terraform.sh
      - pwd
      - ls
      - terraform-backend.sh
      - install-terraform.sh
      - configure-profile-name.sh

  build: 
    commands:
      - ./apply-terraform.sh

  